### ISSUE TITLE
AMD 5800x

### ISSUE THREAD

**Issue by Derik-for-real24** [ancel1x/Ancels-Performance-Batch#4]
my spec; 5800x, Sapphire toxic 6900xt, 32gb (4x3600)

I have a few games that have horrible performance, resulting in unstable overal fps nd frametime

Batman Arkham Knight is able to go from 120fps to the lower 50s, either in 4k or 1440p. The fps fluctuation is massive.

Death Stranding Directors Cut is among the worst, does not matter if its 4k or 1440p, performance is is horible on both resolutions nd very similar, cpu gets pretty toasty too nd cpu utilisation is also high.

Soo I was hoping to find a tool that can help me on games that are hard on the CPU nd give bad performance. But your tool. does not support the AMD 5800x, I mean is my 5800x cpu hardware limited to operate with your tool ?

**Comment by ancel1x** [comment]
No, my tool isn't limited to any cpu, you can use it on any system except linux. On Windows 11, you have to remove the bcdedit commands to make sure it works because those seem to be the cause of issues on 11 when my tool is ran.
