### ISSUE TITLE
Bluetooth doesn't work 

### ISSUE THREAD

**Issue by Galamooth** [ancel1x/Ancels-Performance-Batch#6]
I found a new problem with Bluetooth. The option appears and can be turned on and off. But when pairing/searching for devices it does nothing. If you could help me solve this problem.I thank you.

**Comment by ancel1x** [comment]
Enable these services via registry:

DeviceAssociationBrokerSvc
DevicesFlowUserSvc
DevicePickerUserSvc

**Comment by v2v6** [comment]
we need video for this problem bluetooth please i will use that but i can`t

**Comment by ancel1x** [comment]
I literally left a fix for this issue on top, just enable those services via registry in the services path.

**Comment by v2v6** [comment]
i can’t enable that because i have problems he said the parameters is
incorrect

في خميس، ٢٠ يونيو، ٢٠٢٤ في ٦:٠٢ م، كتب ancel ***@***.***>:
