### ISSUE TITLE
Is this a virus?

### ISSUE THREAD

**Issue by Gelaxiz** [ancel1x/Ancels-Performance-Batch#9]
So I downloaded it now and instantly defender said its an Agent Tesla type of virus and that is a RAT. (Remote access trojan) Is my defender going wild or is it really a virus?
![Screenshot 2024-04-08 222943](https://github.com/ancel1x/Ancels-Performance-Batch/assets/130848366/d0584de4-d56f-47c4-b450-b6a01cd64c2f)
![Screenshot 2024-04-08 223026](https://github.com/ancel1x/Ancels-Performance-Batch/assets/130848366/c26c9764-9bf5-4872-9ea8-4b3ddc9d1443)
![Screenshot 2024-04-08 223044](https://github.com/ancel1x/Ancels-Performance-Batch/assets/130848366/fb3a2e77-0b90-4936-be4a-f54dfe5beb7e)
![Screenshot 2024-04-08 223129](https://github.com/ancel1x/Ancels-Performance-Batch/assets/130848366/925dc702-3f2b-4248-aafa-5ec3a8235940)

**Comment by Wraith82** [comment]
I had problems also I stopped it deleted everything with the file. Somethings not quite right with that file. It will be the last time i download anything from mr Ancel

**Comment by dummys** [comment]
I think you should try to use only the things your understand. As batch file is actually file that you can open with a text editor and look what is inside ... This is definitely not a trojan...

**Comment by Wraith82** [comment]
Well since you understand it it so well how bout you give [Gelaxiz] some instructions to help him instead of using your time to pop of at the mouth?

**Comment by ancel1x** [comment]
It is not a virus, I have a video on this and it's answered in the faq channel of my discord. Virustotal and antiviruses like windows defender don't like things that disable it. If you look at the source code which is available as this is a github page and if you just click edit with notepad on the file since it's batch, you can see it disables defender and you can see every bit of code within it. It is not a virus.

**Comment by dummys** [comment]
> Well since you understand it it so well how bout you give [Gelaxiz] some instructions to help him instead of using your time to pop of at the mouth?

sure I will help someone that don't want to understand what he do ? no thanks, rtfm
